PRODUCTS = [
    {"id": 1, "category": "books", "name": "Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow", "brand": "O'Reilly Media", "price": 3250, "image": "/images/ai-books/ml.jpg"},
    {"id": 2, "category": "books", "name": "Deep Learning (The Bible of Deep Learning)", "brand": "MIT Press", "price": 4500, "image": "/images/ai-books/dl.jpg"},
    {"id": 3, "category": "books", "name": "Artificial Intelligence: A Modern Approach", "brand": "Pearson", "price": 5200, "image": "/images/ai-books/ai.jpg"},
    {"id": 4, "category": "books", "name": "Designing Machine Learning Systems", "brand": "O'Reilly Media", "price": 1500, "image": "/images/ai-books/designing-ml-systems.jpg"},
    {"id": 5, "category": "books", "name": "Machine Learning Engineering", "brand": "True Positive Inc.", "price": 2100, "image": "/images/ai-books/mlops.png"},
    {"id": 6, "category": "books", "name": "Deep Learning with Python (2nd Edition)", "brand": "Manning Publications", "price": 2800, "image": "/images/ai-books/dl-python.jpg"},
    {"id": 7, "category": "books", "name": "Natural Language Processing with Transformers", "brand": "O'Reilly Media", "price": 3400, "image": "/images/ai-books/nlp.jpg"},
    {"id": 8, "category": "books", "name": "Building Machine Learning Powered Applications", "brand": "O'Reilly Media", "price": 2200, "image": "/images/ai-books/applied-ml.jpg"},
    {"id": 9, "category": "books", "name": "Generative AI with Python and TensorFlow 2", "brand": "Packt Publishing", "price": 1800, "image": "/images/ai-books/gen-ai.jpg"},
    {"id": 10, "category": "books", "name": "Probabilistic Machine Learning: An Introduction", "brand": "MIT Press", "price": 4800, "image": "/images/ai-books/advanced-ml.png"},
    {"id": 11, "category": "hardware", "name": "NVIDIA Jetson Orin Nano Developer Kit", "brand": "NVIDIA", "price": 45000, "image": "/images/AI Development Boards/NVIDIA Jetson Orin Nano Developer Kit.jpg"},
    {"id": 12, "category": "hardware", "name": "NVIDIA Jetson Xavier NX Developer Kit", "brand": "NVIDIA", "price": 38000, "image": "/images/AI Development Boards/NVIDIA Jetson Xavier NX Developer Kit.jpg"},
    {"id": 13, "category": "hardware", "name": "NVIDIA Jetson AGX Orin Developer Kit", "brand": "NVIDIA", "price": 185000, "image": "/images/AI Development Boards/NVIDIA Jetson AGX Orin Developer Kit.jpg"},
    {"id": 14, "category": "hardware", "name": "Raspberry Pi 5 Model B (8GB RAM)", "brand": "Raspberry Pi Foundation", "price": 7800, "image": "/images/AI Development Boards/Raspberry Pi 5 (8GB).jpg"},
    {"id": 15, "category": "hardware", "name": "Google Coral Dev Board", "brand": "Google", "price": 12500, "image": "/images/AI Development Boards/Google Coral Dev Board.jpg"},
    {"id": 16, "category": "hardware", "name": "Google Coral USB Accelerator", "brand": "Google", "price": 7200, "image": "/images/AI Development Boards/Google Coral USB Accelerator.jpg"},
    {"id": 17, "category": "hardware", "name": "BeagleBone AI-64", "brand": "BeagleBoard.org", "price": 11800, "image": "/images/AI Development Boards/BeagleBone AI-64.jpg"},
    {"id": 18, "category": "hardware", "name": "Arduino Portenta X8", "brand": "Arduino", "price": 22500, "image": "/images/AI Development Boards/Arduino Portenta X8.jpg"},
    {"id": 19, "category": "hardware", "name": "STM32N6 Discovery Kit", "brand": "STMicroelectronics", "price": 20000, "image": "/images/AI Development Boards/STM32N6 Discovery Kit.jpg"},
    {"id": 20, "category": "hardware", "name": "Intel Neural Compute Stick 2", "brand": "Intel", "price": 8500, "image": "/images/AI Development Boards/Intel Neural Compute Stick 2.jpg"},
    {"id": 21, "category": "assistants", "name": "Apple HomePod (2nd Generation)", "brand": "Apple", "price": 32900, "image": "/images/ai-assistants/siri.jpg"},
    {"id": 22, "category": "assistants", "name": "Amazon Echo (4th Generation)", "brand": "Amazon", "price": 9999, "image": "/images/ai-assistants/alexa.jpg"},
    {"id": 23, "category": "assistants", "name": "Amazon Echo Dot (5th Generation)", "brand": "Amazon", "price": 5499, "image": "/images/ai-assistants/alexa-5gen.jpg"},
    {"id": 24, "category": "assistants", "name": "Amazon Echo Show 8 (3rd Gen)", "brand": "Amazon", "price": 14999, "image": "/images/ai-assistants/alexa-echo 8.jpg"},
    {"id": 25, "category": "assistants", "name": "Google Nest Audio", "brand": "Google", "price": 7999, "image": "/images/ai-assistants/google-assistant.jpg"},
    {"id": 26, "category": "assistants", "name": "Google Nest Hub (2nd Generation)", "brand": "Google", "price": 8999, "image": "/images/ai-assistants/Google Nest Hub (2nd Gen).jpg"},
    {"id": 27, "category": "assistants", "name": "Google Nest Mini", "brand": "Google", "price": 4499, "image": "/images/ai-assistants/Google Nest Mini.jpg"},
    {"id": 28, "category": "assistants", "name": "Apple HomePod Mini", "brand": "Apple", "price": 9900, "image": "/images/ai-assistants/Apple HomePod Mini.jpg"},
    {"id": 29, "category": "assistants", "name": "Lenovo Smart Clock Essential (Alexa)", "brand": "Lenovo", "price": 4299, "image": "/images/ai-assistants/Lenovo Smart Clock Essential.jpg"},
    {"id": 30, "category": "assistants", "name": "JBL Authentics 500 High-Fidelity Speaker", "brand": "JBL", "price": 59999, "image": "/images/ai-assistants/JBL Authentics 500 Smart Speaker.jpg"},
]

CATEGORY_NAMES = {
    "books": "AI Books",
    "hardware": "AI Hardware Devices",
    "assistants": "AI Smart Assistants",
}
